from enum import IntEnum


class ExitCode(IntEnum):
    INVALID_LANGUAGE_SPT = 100
    INVALID_LANGUAGE_TRANS = 101
    INVALID_LANGUAGE_TTS = 102
    INVALID_FILEFORMAT = 103
    MISSING_HF_KEY = 104
    NO_FFMPEG = 105
    NO_TTS_API_SERVER = 110
    NO_OPENAI_TTS = 112
    NO_OPENAI_KEY = 113
